### ISSUE TITLE
FBA and cfw 2.0 beta issues

### ISSUE THREAD

**Issue by Baodejia** [Rezzy-dev/fba-miyoo-playable#5]
On Powkiddy V/Q90
hello FBA  with Neogeo ALL roms are loading and works as it should with cfw 1.3.3 (overclocked at 894Mhz) but with CFW 2 (uclibc) there is 2 issues, the first the names of the game are not all displayed on the roms list (only name with .zip eg:wh1.zip) and the second issues is all games with 8Mb  (8192Kb) chunk inside zip folder doesn't boot (it stuck at loading 265-c2.bin ...8192Kb graphics (eg: kof 2002) 
I tried with overclocked an underclocked apps (between 600Mhz to 960Mhz), same result
Thanks

**Comment by Apaczer** [comment]
They do work, but they load for ages with BTRFS (new filesystem for MiyooCFW 2.0). I suggest you use GnGeo emulator for AES/MVS. 
For the names displaying, there was wrong path specified for `aliases.txt` file I believe, it should be correct now. Simply change this line in `fba.lnk` to look like this:
```
selectoraliases=/mnt/emus/fba/aliases.txt
```
